version: '3.7'

services:
  e-commerce-backend-app:
    image: e-commerce-backend-app:production-latest
    depends_on:
    - mongodb
    secrets:
      - admin-username
      - admin-password
      - mongodb-username
      - mongodb-password
    deploy:
      endpoint_mode: dnsrr
      replicas: 1

  mongodb:
    image: mongo:4.0.2
    volumes:
      - mongodb-volume:/data/db
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb-password
    secrets:
      - mongodb-username
      - mongodb-password
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == worker

secrets:
  mongodb-username:
     external: true

  mongodb-password:
     external: true

  admin-username:
     external: true

  admin-password:
     external: true

networks:
  default:
    name: net

volumes:
  mongodb-volume:
